# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-15 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0002_authgroup_authgrouppermissions_authpermission_authusergroups_authuseruserpermissions_djangoadminlog_'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='navigation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertyvalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shopcar',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shopimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='submenu2',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
